export const {
  new_lobby,
  new_player,
  joined_lobby,
  player_left,
  match_started,
  get_hand,
  roll_dice,
  turn_passed,
  player_position,
  question,
  reset_question,
  suspect_response,
  reset_suspect_response,
  player_deleted,
  reset_loser,
  new_message,
  failed,
  reset_lobby,
} = {
  new_lobby: "new_lobby",
  new_player: "new_player",
  joined_lobby: "joined_lobby",
  player_left: "player_left",
  match_started: "match_started",
  get_hand: "get_hand",
  roll_dice: "roll_dice",
  turn_passed: "turn_passed",
  player_position: "player_position",
  question: "question",
  reset_question: "reset_question",
  suspect_response: "suspect_response",
  reset_suspect_response: "reset_suspect_response",
  player_deleted: "player_deleted",
  reset_loser: "reset_loser",
  new_message: "new_message",
  failed: "failed",
  reset_lobby: "reset_lobby",
};
